<?xml version="1.0" encoding="utf-8"?>
<robot name="akros2_diff" xmlns:xacro="http://ros.org/wiki/xacro">
<xacro:include filename="$(find akros2_description)/urdf/akros2_diff/robot.common.xacro"/>
<xacro:include filename="$(find akros2_description)/urdf/akros2_diff/robot.control.xacro"/>
<xacro:include filename="$(find akros2_description)/urdf/akros2_diff/robot.gazebo.xacro"/>

<xacro:arg name="mesh_path" default="package://akros2_description/meshes/akros2_diff/" /> <!-- HTTPS URL also works here -->
<xacro:arg name="nopath" default="false" />
<xacro:property name="mesh_path" value="$(arg mesh_path)" />

<xacro:if value="$(arg nopath)">
  <xacro:property name="mesh_path" value="" />
</xacro:if>

<!-- **** LINKS **** -->

<!-- BASE_LINK -->
<link name="base_link">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <mesh filename="${mesh_path}base_module.dae" />
    </geometry>
    <material name="BaseLinkColor"/>
  </visual>
  <collision>
    <origin xyz="0 0 ${base_center_offset_z}" rpy="0 0 0" />
    <geometry>
      <cylinder length="${base_height}" radius="${base_radius}"/>
    </geometry>
  </collision>
</link>

<!-- BASE_LINK_INERTIAL (WORKAROUND FOR KDL WHICH DOES NOT ACCEPT BASE_LINK WITH INERTIA) -->
<link name="base_link_inertial">
  <inertial>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <mass value="${base_mass}"/>
    <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_height}"/>
  </inertial>
</link>

<!-- BASE_FOOTPRINT -->
<link name="base_footprint"/>

<!-- BNO055 IMU_LINK -->
<link name="imu_link"/>

<!-- WHEEL LEFT -->
<link name="wheel_l">
  <inertial>
    <mass value="${wheel_mass}"/>
    <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_thickness}"/>
  </inertial>
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <mesh filename="${mesh_path}omniwheel.dae" />
    </geometry>
    <material name="WheelsNavColor"/>
  </visual>
  <collision>
    <origin xyz="${wheel_thickness/2} 0 0" rpy="0 ${pi_by_two} 0" />
    <geometry>
      <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
    </geometry>
  </collision>
</link>

<!-- WHEEL RIGHT -->
<link name="wheel_r">
  <inertial>
    <mass value="${wheel_mass}"/>
    <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_thickness}"/>
  </inertial>
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
      <mesh filename="${mesh_path}omniwheel.dae" />
    </geometry>
    <material name="WheelsNavColor"/>
  </visual>
  <collision>
    <origin xyz="${wheel_thickness/2} 0 0" rpy="0 ${pi_by_two} 0" />
    <geometry>
      <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
    </geometry>
  </collision>
</link>

<!-- **** JOINTS **** -->

<!-- BASE_LINK_INERTIAL TO BASE_LINK -->
<joint name="base_inertial_fixed" type="fixed">
  <parent link="base_link"/>
  <child link="base_link_inertial"/>
  <origin xyz="0 0 0"/>
</joint>

<!-- BASE_FOOTPRINT TO BASE_LINK -->
<joint name="base_footprint_fixed" type="fixed">
  <parent link="base_link"/>
  <child link="base_footprint"/>
  <origin xyz="0 0 ${footprint_base_offset_z}"/>
</joint>

<!-- IMU_LINK TO BASE_LINK -->
<joint name="imu_base_fixed" type="fixed">
  <parent link="base_link"/>
  <child link="imu_link"/>
  <origin xyz="0 0 ${imu_offset_z}"/>
</joint>

<!-- WHEEL_L TO BASE_LINK -->
<joint name="joint_l" type="continuous">
  <parent link="base_link" />
  <child link="wheel_l" />
  <origin xyz="${joint_lr_offset_x} ${joint_lr_offset_y} ${joint_offset_z}" rpy="0 0 ${2*pi_by_three}" />
  <axis xyz="1 0 0" />
</joint>

<!-- WHEEL_R TO BASE_LINK -->
<joint name="joint_r" type="continuous">
  <parent link="base_link" />
  <child link="wheel_r" />
  <origin xyz="${joint_lr_offset_x} ${-1*joint_lr_offset_y} ${joint_offset_z}" rpy="0 0 ${-2*pi_by_three}" />
  <axis xyz="1 0 0" />
</joint>

</robot>
